Repository AY2324S2-CS2103T-W12-1/tp, pull requests merged in 2024-03, with the labels that each got.

#47 Add ReganChoy AboutUs Info
  docs/team/reganchoy.md
  src/main/java/seedu/address/logic/parser/MetCommandParser.java
Labels: type.Documentation

#49 Add solomonng aboutus info
  docs/AboutUs.md
  docs/images/solomonng2001.png
  docs/team/solomonng.md
Labels: type.Documentation

#48 Update DG Requirements
  docs/DeveloperGuide.md
Labels: type.Documentation

#51 Add Yorklim AboutUs Info
  docs/AboutUs.md
  docs/images/yorklim.jpg
  docs/team/yorklim.md
Labels: type.Documentation

#52 Add User stories to DevGuide
  docs/DeveloperGuide.md
Labels: type.Documentation

#53 Update developer guide requirements
  docs/DeveloperGuide.md
Labels: type.Documentation

#50 Update readme and contextualise to clientcare
  README.md
  docs/images/Ui.png
Labels: type.Documentation

#56 Update About Us Image Name
  docs/AboutUs.md
  docs/images/johndoe.png
  docs/images/yorklim.png
Labels: type.Documentation

#55 Update developer guide requirements
  docs/DeveloperGuide.md
Labels: type.Documentation

#59 Fix product name in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#61 Update DG Use Cases
  docs/DeveloperGuide.md
Labels: type.Documentation

#63 Add Birthday
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Testing, priority.Medium

#64 Add LastMet, Schedule, Mark Functionality
  src/main/java/seedu/address/commons/util/DateTimeUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LastMetCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/FutureDateException.java
  src/main/java/seedu/address/logic/commands/exceptions/PastDateException.java
  src/main/java/seedu/address/logic/commands/exceptions/ScheduleAlreadyDoneException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LastMetCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/person/LastMet.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/DateTmeUtilTest.java
  src/test/java/seedu/address/logic/commands/LastMetCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/LastMetCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/model/person/LastMetTest.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Enhancement, priority.Medium

#68 Add addPolicy command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LastMetCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddPolicyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PolicyList.java
  src/main/java/seedu/address/model/person/exceptions/PolicyNotFoundException.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/main/java/seedu/address/model/policy/PolicyType.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicy.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPolicyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/policy/PolicyListTest.java
  src/test/java/seedu/address/model/policy/PolicyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Testing, priority.Medium

#66 Add Client View Panel GUI and View Client Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/LastMetCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/DisplayClient.java
  src/main/java/seedu/address/ui/ClientDetailsCard.java
  src/main/java/seedu/address/ui/ClientListCard.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/ClientPolicyTable.java
  src/main/java/seedu/address/ui/ClientViewPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/ClientDetailsCard.fxml
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/ClientListPanel.fxml
  src/main/resources/view/ClientPolicyTable.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Story, type.Testing, priority.High

#72 Update UG and UI UML in DG
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  src/main/resources/view/MainWindow.fxml
Labels: type.Documentation, type.Story

#77 Update DG class diagrams and user stories
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation, type.Story

#76 Add LastMet and Schedule into the User Guide
  docs/UserGuide.md
Labels: type.Documentation, type.Story

#80 Integrate Policy with GUI
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/PolicyList.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicy.java
  src/main/java/seedu/address/ui/ClientPolicyTable.java
  src/main/java/seedu/address/ui/ClientViewPanel.java
  src/main/resources/view/ClientPolicyTable.fxml
  src/test/java/seedu/address/model/person/PolicyListTest.java
  src/test/java/seedu/address/model/policy/PolicyTest.java
Labels: type.Enhancement, priority.Medium, type.Chore

#81 Add Addpolicy and Deletepolicy into the User Guide
  docs/UserGuide.md
Labels: type.Story, priority.Medium

#86 Update build jar filename
  build.gradle
Labels: type.Chore

#88 Update developer and user guide
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: type.Documentation, priority.High

#90 Add reminder feature
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/LastMet.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/reminder/ReminderList.java
  src/main/java/seedu/address/model/reminder/ReminderType.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RemindersCard.java
  src/main/java/seedu/address/ui/RemindersPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/LastMetTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
  src/test/java/seedu/address/model/reminder/ReminderListTest.java
  src/test/java/seedu/address/model/reminder/ReminderTypeTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement, type.Testing, priority.High

#92 Add page breaks to UG
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: type.Documentation, priority.Medium

#94 Updates to UG
  docs/UserGuide.md
  docs/images/ug/GUI v1.2 Graphic.png
  docs/stylesheets/main.css
Labels: type.Documentation, priority.Medium

#95 Enable assertions
  build.gradle
Labels: priority.Medium

#96 Update UG Formatting
  docs/UserGuide.md
Labels: type.Documentation

#99 Update UG for v1.3
  docs/UserGuide.md
  docs/images/ug/GUI v1.2 Graphic.png
  docs/images/ug/addclient.png
  docs/images/ug/doubleclick.png
  docs/images/ug/error.png
  docs/images/ug/schedule.png
  docs/images/ug/success_add.png
  docs/images/ug/success_schedule.png
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Documentation, priority.Medium

#97 Update ug user friendly
  docs/UserGuide.md
  docs/images/ug/bypassPromptMacOS.png
  docs/images/ug/commandStructure.png
  docs/images/ug/confirmOpenMacOS.png
  docs/images/ug/startUpAppMacOS.png
  docs/images/ug/unidentifiedDeveloperMacOS.png
Labels: type.Documentation, priority.High

#100 Fix UG Formatting
  docs/UserGuide.md
  docs/images/ug/commandStructure.jpg
Labels: type.Documentation, priority.Medium

#93 Add sorting for person attributes
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/LastMet.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/PersonComparator.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Priority.java
  src/main/java/seedu/address/model/person/PriorityValue.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/SortCriteria.java
  src/main/java/seedu/address/model/person/SortOrder.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/LastMetTest.java
  src/test/java/seedu/address/model/person/PersonComparatorTest.java
  src/test/java/seedu/address/model/person/PriorityTest.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
  src/test/java/seedu/address/model/person/SortCriteriaTest.java
  src/test/java/seedu/address/model/person/SortOrderTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, type.Testing, priority.High

#102 Update DG for LastMet
  docs/DeveloperGuide.md
  docs/diagrams/LastMetObjectDiagram.puml
  docs/diagrams/LastMetSequenceDiagram.puml
Labels: type.Documentation

#104 Add logging
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#103 Add explanation on extensions to add and edit command (birthday and priority)
  docs/DeveloperGuide.md
  docs/diagrams/AddPersonObjectDiagram.puml
  docs/diagrams/AddPersonSequenceDiagram.puml
Labels: type.Documentation, priority.High

#105 Add birthday reminders
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/reminder/ReminderList.java
  src/main/java/seedu/address/model/reminder/ReminderType.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RemindersPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/reminder/ReminderListTest.java
  src/test/java/seedu/address/model/reminder/ReminderTypeTest.java
Labels: type.Enhancement, type.Testing, priority.High

#106 Add view command to DG
  docs/DeveloperGuide.md
  docs/diagrams/ViewClientSequenceDiagram.puml
Labels: type.Documentation
