Repository AY2324S2-CS2103T-W12-1/tp, pull requests merged in 2024-04, with the labels that each got.

#108 Refactor sorting of person list
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeletePolicyCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/LastMetCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/PersonComparator.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/LastMetCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonComparatorTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.Bug, type.Chore, severity.High

#109 Fix birthday sorting regardless of year bug
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Testing, type.Chore, severity.High

#107 Set Command
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/LastMetCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/person/LastMet.java
  src/main/java/seedu/address/storage/SetStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/SetCommandTest.java
  src/test/java/seedu/address/logic/parser/SetCommandParserTest.java
Labels: type.Story, priority.Medium

#113 Update GUI for Client Details
  docs/images/Ui.png
  src/main/java/seedu/address/ui/ClientDetailsCard.java
  src/main/resources/view/ClientDetailsCard.fxml
Labels: type.Documentation

#116 Fix-dates-and-display-messages
  src/main/java/seedu/address/commons/util/DateTimeUtil.java
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/LastMetCommandParser.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/person/Birthday.java
Labels: type.Bug, priority.High, type.Chore, severity.High

#123 Add diagrams in user guide for reminders, policies, client view and c…
  docs/UserGuide.md
  docs/images/ug/clientViewAndList.png
  docs/images/ug/policies.png
  docs/images/ug/reminders.png
Labels: type.Documentation

#174 Fix grammar and space error in addpolicy and deletepolicy
  src/main/java/seedu/address/logic/commands/DeletePolicyCommand.java
  src/main/java/seedu/address/model/policy/Policy.java
Labels: type.Documentation

#177 Update UG for v1.4
  docs/UserGuide.md
  docs/images/ug/addpolicyA.png
  docs/images/ug/clear.png
  docs/images/ug/clientViewAndList.png
  docs/images/ug/delete.png
  docs/images/ug/deletepolicyA.png
  docs/images/ug/edit.png
  docs/images/ug/find.png
  docs/images/ug/list.png
  docs/images/ug/mark.png
  docs/images/ug/met.png
  docs/images/ug/remark.png
  docs/images/ug/scheduleA.png
  docs/images/ug/set.png
  docs/images/ug/sort.png
  docs/images/ug/success_addpolicyA.png
  docs/images/ug/success_clear.png
  docs/images/ug/success_delete.png
  docs/images/ug/success_deletepolicyA.png
  docs/images/ug/success_edit.png
  docs/images/ug/success_find.png
  docs/images/ug/success_list.png
  docs/images/ug/success_mark.png
  docs/images/ug/success_met.png
  docs/images/ug/success_remark.png
  docs/images/ug/success_scheduleA.png
  docs/images/ug/success_set.png
  docs/images/ug/success_sort.png
  docs/images/ug/success_view.png
  docs/images/ug/view.png
Labels: type.Documentation, priority.High

#178 Update DG for v1.4
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#182 Update sorting, user guide and json path
  docs/UserGuide.md
  docs/images/ug/ReleaseTag v1.2.png
  docs/images/ug/clientViewAndList.png
  docs/images/ug/clientcare jar file v1.2.png
  docs/images/ug/commandStructure.jpg
  docs/images/ug/commandStructure.png
  docs/images/ug/policies.png
  docs/images/ug/reminders.png
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/model/person/PersonComparator.java
  src/main/java/seedu/address/model/person/SortCriteria.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonComparatorTest.java
  src/test/java/seedu/address/model/person/SortCriteriaTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Bug, type.Documentation, type.Testing, priority.High, type.Chore

#183 Update UG and DG for v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ug/error_command.png
  docs/images/ug/error_commandformat.png
  docs/images/ug/error_futuremet.png
  docs/images/ug/error_index.png
  docs/images/ug/error_phone.png
Labels: type.Documentation, type.Enhancement, priority.High

#184 Update Use Cases in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#187 Fix or update minor add ins in ug
  docs/UserGuide.md
Labels: type.Documentation, severity.Low

#189 DG Update
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#193 Add DG implementation details for sorting, birthday and priority
  docs/DeveloperGuide.md
  docs/diagrams/AddPersonObjectDiagram.puml
  docs/diagrams/AddPersonSequenceDiagram.puml
  docs/diagrams/SortPersonsObjectDiagram.puml
  docs/diagrams/SortPersonsSequenceDiagram.puml
Labels: type.Documentation, priority.Medium

#192 Update DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium

#196 Add Remark Use Case and Update Planned Enhancements
  docs/DeveloperGuide.md
Labels: type.Documentation

#197 Add sort test cases and effort in developer guide
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium
